### ISSUE TITLE
BSU

### ISSUE THREAD

**Issue by kventinel** [kventinel/BSU#2]
You can add all your tasks from all your courses here:)

**Comment by aandrukhovich** [comment]
#5
Это графы 25-ая, прогулка

**Comment by aandrukhovich** [comment]
#6 
Ой, это на самом деле 42-ая задача из структур данных, а я подписал её как 8-ую.

**Comment by aandrukhovich** [comment]
#7 
А вот это уже правильная 8-ая.
прости, что перепутал :(

**Comment by kventinel** [comment]
@aandrukhovich Спасибо тебе за пуши.;)

**Comment by aandrukhovich** [comment]
@kventinel :heart:
