### ISSUE TITLE
Add tasks from BSU course Theory of algorithms.

### ISSUE THREAD

**Issue by kventinel** [kventinel/BSU#3]
Деревья поиска.

Необходимо найти наибольший полупуть между вершинами разной высоты с минимальной суммой ключей крайних вершин. Если таких полупутей несколько, то выбрать из них тот, у которого корневая вершина имеет наименьшее ключевое значение. Удалить (правым удалением), если существует, среднюю по значению вершину этого полупути.

Если у вершины отсутствует некоторое поддерево, то его высоту полагаем равной −1.

**Comment by aandrukhovich** [comment]
Вроде нашел, проверяй :1st_place_medal: 
#4

**Comment by kventinel** [comment]
@aandrukhovich А тесты прошли?

**Comment by aandrukhovich** [comment]
@kventinel  Обижаешь :)
![image](https://user-images.githubusercontent.com/13490190/32022304-9db374ae-b9de-11e7-86ad-f83150d2bdae.png)
